load_defaults: 7.32.0
development:
  adapter: solr
  #url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>
  url: <%= ENV['SOLR_URL'] || "http://192.168.1.164:8983/solr/test4" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://127.0.0.1:8983/solr/blacklight-core" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "https://solr2020.library.albany.edu:8984/solr/arclight_daos" %>
