meg:
  name: 'M.E. Grenander Department of Special Collections & Archives'
  description: 'The principal purpose of The M. E. Grenander Department of Special Collections and Archives is to collect, preserve, provide access to, exhibit, and encourage use of the University Libraries unique manuscript and archival materials, the official records of the University, rare books, and printed materials. These materials are acquired by gift or purchase and serve the current and future research interests of faculty, students, and others affiliated with the University as well as other researchers from the region and beyond.'
  building: 'Science Library'
  address1: 'SL-356'
  address2: '1400 Washington Ave'
  city: 'Albany'
  state: 'NY'
  zip: '12222'
  country: 'USA'
  phone: '(518) 437-3935'
  contact_info: ''
  thumbnail_url: 'https://archives.albany.edu/web/img/700/mpa700.jpg'
  google_request_url: 'https://archives.albany.edu/web/reference'
  google_request_mappings: "document_url=link&collection_name=collection&eadid=eadid&containers=containers&title=title"
  visit_note: "The archives are open to the public and anyone is welcome to visit and view the collections."
schs:
  name: 'Schenectady County Historical Society'
  description: 'Schenectady County Historical Society’s digital collection on New York Heritage features a sample of our holdings. Our full collection includes artifacts, paintings, books pertaining to local history, family histories, diaries, newspapers, yearbooks, maps, photographs, personal and family papers, and much more. The mission of the Schenectady County Historical Society is to share stories, inspire dialogue, and encourage the understanding of the history, people, and cultures of Schenectady County. The Society features interactive exhibits, talks, workshops, concerts, education programs, and community events for all audiences in order to further our mission. Our headquarters is located in Schenectady’s historic Stockade neighborhood and houses both the Schenectady History Museum and the Grems-Doolittle Library. The Historical Society also operates the Mabee Farm Historic Site in Rotterdam Junction. We encourage you to visit the Schenectady County Historical Society to explore how Schenectady County has changed over the years, the impact the Schenectady area has had on national events, as well as the rich and diverse history that Schenectady County has to offer.'
  building: 'Grems-Doolittle Library'
  address1: '32 Washington Ave.'
  address2: ''
  city: 'Schenectady'
  state: 'NY'
  zip: '12305'
  country: 'USA'
  phone: '(518) 374-0263'
  contact_info: 'Librarian@schenectadyhistorical.org'
  thumbnail_url: 'https://nyheritage.org/sites/default/files/styles/org_logo_extra/public/content/organization/logos/CDLC031.png?itok=kRRavQD9'
  google_request_url: 'https://archives.albany.edu/web/reference'
  google_request_mappings: "document_url=link&collection_name=collection&eadid=eadid&containers=containers&title=title"
  visit_note: "Please send questions to Librarian@schenectadyhistorical.org"
